### ISSUE TITLE
It was a good game!

### ISSUE THREAD

**Issue by Sukaato** [angeluriot/Hexawar.io#15]
![unknown](https://user-images.githubusercontent.com/44368476/182218558-34af2030-5929-4a0f-9b74-bed2eddf3870.png)

**Comment by Xenxia** [comment]
But the grid is to small 😂

**Comment by Sukaato** [comment]
![Capture d’écran 2022-08-01 220535](https://user-images.githubusercontent.com/44368476/182235566-aaf5f973-bff2-4bc7-ae35-aaae615ba48a.jpg)
I defeated your bots

**Comment by angeluriot** [comment]
It's only a not maintained school project
